#!/bin/sh
#
# File:    estimnetdirectedEstimation2simulationConfig.sh
# Author:  Alex Stivala
# Created: November 2019
#
#
# Read output of computeEstimNetDirectedCovariance.R with the estimate
# computed from EstimNetDirected results
# and build config script for SimulateERGM to simulate networks from
# the estimated parmeter values.
# 
# Usage: estimnetdirectedEstimation2simulationConfig.sh estimationoutputfile
#
# E.g.:
#   estimnetdirectedEstimation2simulationConfig.sh  estimation.out
#
# Output is to stdout
#
# Uses various GNU utils options on echo, etc.



if [ $# -ne 1 ]; then
    echo "usage: $0 estimation.out" >&2
    exit 1
fi

estimationresults=$1

estimnet_tmpfile=`mktemp`

echo "# Generated by: $0 $*"
echo "# At: " `date`
echo "# On: " `uname -a`


# new version has results starting at line following "Pooled" at start
# of line (pooling the individual run estimates values printed earlier) and
# 5 columns:
# Effect   estimate   sd(theta)   est.std.err  t.ratio
# (and maybe *) plus
# TotalRuns and ConvergedRuns e.g.:
#Diff_completion_percentage -0.002270358 0.005812427 0.01295886 0.021386
#TotalRuns 2
#ConvergedRuns 2
# (see computeEstimNetDirectedCovariance.R)
# https://unix.stackexchange.com/questions/78472/print-lines-between-start-and-end-using-sed
cat ${estimationresults} | sed -n -e '/^Pooled/,/^TotalRuns/{//!p}'  | tr -d '*' | fgrep -vw AcceptanceRate | fgrep -vw TotalRuns | fgrep -vw ConvergedRuns | awk '{print $1,$2,$4,$5}'  |  tr ' ' '\t' >> ${estimnet_tmpfile}

effectlist=`cat ${estimnet_tmpfile} |  awk '{print $1}' | sort | uniq`

for effect in ${effectlist}
do
  estimnet_point=`grep -w ${effect} ${estimnet_tmpfile} | awk '{print $2}'`
  echo $effect $estimnet_point #XXX
done


rm ${estimnet_tmpfile}
